# Generated by Django 6.0.3 on 2026-03-12 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='title',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('working', 'Working'), ('done', 'Done')], default='pending', max_length=55),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=55),
        ),
    ]
