# Generated by Django 6.0.3 on 2026-03-12 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_apirequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='work',
            field=models.CharField(max_length=55),
        ),
    ]
